// constants/products.ts
import { Products } from "@/types/Productdetails";
export const productsdetail: Products[] = [
  {
    slug: "new-sale",
    name: "1.New and sale badge",
    image: "/img/product1.jpg",
    sku: "1511",
    stock: 7,
    oldPrice: 130,
    price: 110,
    unitPrice: "$27.50 / 2 g",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC...",
    sizes: ["s", "m", "l", "xl"],
    colors: ["red", "green", "blue", "yellow", "white"],
    category: ['Chair',  'Featured Product'],
    categories: [
      "/img/product1.jpg",
      "/img/product2.jpg",
      "/img/product3.jpg",
      "/img/product1.jpg",
      "/img/product2.jpg",
      "/img/product3.jpg",
    ],
  },
  
  {
    slug: "new-badge",
    name: "2. New badge product",
    price: 80.0,
    sku: "1110",
    stock: 10,
    image: "/img/product2.jpg",
    description: "This product contains a demo video showcase.",
    sizes: ["m", "l","xl","xxl"],
     category: ['Chair','Featured Product'],
    colors: ["gold", "gray","pink","blue"],
    categories: ["/img/product2.jpg",
      "/img/product5.jpg",
      "/img/product7.jpg",
      "/img/product8.jpg"
    ],
  },

  {
    slug: "Variable-product",
    name: "3. Variable Product",
    sku: "1110",
    stock: 9,
    price:70,
    oldPrice: 85,
    description: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
    sizes: ["m", "l","s","xl"],
     category: ['Chair', 'Deals Product',],
    colors: ["black", "gray","pink","blue"],
    categories: ["/img/product3.jpg","/img/product5.jpg",
      "/img/product7.jpg",
      "/img/product8.jpg"],
    image: "/img/product3.jpg",
  },
  {
    slug: "Soldout-product",
    name: "4. Soldout product",
    sku: "501",
    stock:0,
    price:19,
    oldPrice:29,
    description: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
    sizes: ["m", "l"],
    category: ['Deals Product', 'Featured Product'],
    colors: ["black", "gray"],
    categories: ["/img/product4.jpg","/img/product1.jpg",
      "/img/product4.jpg",
      "/img/product6.jpg"],
    image: "/img/product4.jpg",
  },
  {
    slug: "Simple-Product",
    name: "5. Simple Product",
    sku: "101",
    stock: 8,
    price: 50,
    description: "On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will",
    sizes: [],
     category: ['Chair', 'Deals Product', 'Featured Product'],
    colors: [],
    categories: ["/img/product5.jpg","/img/product10.jpg",
      "/img/product11.jpg",
      "/img/product12.jpg"],
    image: "/img/product5.jpg",
  },
  {
    slug: "Sample-affiliate-product",
    name: "6. Sample affiliate product",
    sku: "1520",
    stock: 0,
    price: 29,
    description: "This product contains a demo video showcase.",
    sizes: ["m", "l"],
     category: ['Chair', 'Deals Product', 'Featured Product'],
    colors: ["black", "gray"],
    categories: ["/img/product6.jpg","/img/product5.jpg",
      "/img/product9.jpg",
      "/img/product4.jpg"],
    image: "/img/product6.jpg",
  },
  
  {
    slug: "Variable-With-Soldout",
    name: "7. Variable With Soldout",
    sku: "204",
    stock: 6,
    price: 55,
    oldPrice:75,
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    sizes: ["m", "l"],
     category: ['Deals Product'],
    colors: ["red", "blue"],
    categories: ["/img/product7.jpg"],
    image: "/img/product7.jpg",
  },
  {
    slug: "Withoutshortcode",
    name: "9. Without shortcode",
    sku: "1520",
    stock: 12,
    price: 220,
    description: "This product contains a demo video showcase.",
    sizes: ["m", "l"],
     category: ['Chair', 'Deals Product', 'Featured Product'],
    colors: ["black", "gray"],
    categories: ["/img/product8.jpg"],
    image: "/img/product9.jpg",
  },

  {
    slug: "Countdown-Product",
    name: "10. Countdown Product",
    sku: "3010",
    stock: 14,
    price: 39,
    oldPrice:60,
    description: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
    sizes: ["m", "l"],
     category: ['Chair', 'Deals Product', 'Featured Product'],
    colors: ["black", "gray"],
    categories: ["/img/product10.jpg"],
    image: "/img/product10.jpg",
  },
{
    slug: "video",
    name: "11.Product with video",
    image: "/img/product_11.jpg",
    sku: "9911",
    stock: 1,
    price: 39,
    description: "As opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for....",

    category: ['Chair', 'Deals Product', 'Featured Product'],
    colors: ["black", "gray","yellow","purple"],
    categories: ["/img/product_11.jpg","/img/product2.jpg",
      "/img/product_11.jpg",],
  },
  {
    slug: "Demo-product-title",
    name: "12. Demo product title",
    sku: "1520",
    stock: 0,
    price: 29,
    description: "This product contains a demo video showcase.",
    sizes: ["m", "l"],
     category: ['Chair', 'Deals Product', 'Featured Product'],
    colors: ["black", "gray"],
    categories: ["/img/product-video.jpg"],
    image: "/img/product12.jpg",
  },
];
